spring.application.name=kams
spring.config.import=optional:file:.env[.properties]

# DATABASE
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=${POSTGRES_SCHEMA}

# HIKARI POOL
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=604800000

# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# CLOUD STORAGE
#cloudflare.r2.access-key=${CLOUDFLARE_R2_ACCESS_KEY}
#cloudflare.r2.secret-key=${CLOUDFLARE_R2_SECRET_KEY}
#cloudflare.r2.bucket=${CLOUDFLARE_R2_BUCKET_NAME}
#cloudflare.r2.endpoint=${CLOUDFLARE_R2_ENDPOINT_URL}
#cloudflare.r2.public-url=${CLOUDFLARE_R2_PUBLIC_URL}

# FILE UPLOAD
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB
spring.servlet.multipart.enabled=true


# LOGGING
logging.level.itsdax.evmak=DEBUG
